# Site
repository: sproogen/resume-theme
favicon: images/favicon.ico

# Content configuration version
version: 2

# Personal info
name: Marat Saidov
title: MLOps & NLP Research Engineer
email: marat.a.saidov@gmail.com
#website: www.github.com/maratsaidov/

# Dark Mode (true/false/never)
darkmode: false

# Social links
#twitter_username: facespics
github_username:  maratsaidov
# stackoverflow_username: "00000001"
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
instagram_username: _msaidov_
linkedin_username: msaidov
# xing_username: jekyll
# pinterest_username: jekyll
#youtube_username: globalmtb
# googleplus_username: +jekyll
# orcid_username: 0000-0000-0000-0000

# Additional icon links
#additional_links:
#- title: itsgoingto.be
#  icon: fas fa-globe
#  url: https://www.itsgoingto.be
# - title: another link
#   icon: font awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&m=free)
#   url: Link url (eg. https://google.com)

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
# about_title: About Me
about_profile_image: images/profile.jpg
about_content: | # this will include new lines to allow paragraphs
  Hi, my name's Marat and I'm a Machine Learning Engineer.
  I am most skilled in: <mark>NLP</mark>.

content:
  - title: Projects # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: top-middle
        title: Artificial Text Detection
        link: github.com/maratsaidov
        # link_text: Project Website
        additional_links:
          - title:  maratsaidov/artificial-text-detection
            icon: fab fa-github
            url: github.com/maratsaidov/artificial-text-detection
          # - title:  Github page for project (eg. sproogen/modern-resume-theme)
          #   icon: fab fa-github
          #   url: Link to project (eg. sproogen.github.io/modern-resume-theme)
        quote: >
          My BSc thesis. I studied the ability of language models to distinguish artificial texts from human-written.
        description: | # this will include new lines to allow paragraphs
          As well as BSc, this project correlates with my research at CPLab.

  - title: Experience # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: SBDA Group
        link: sbdagroup.com
        # link_text: boringcompany.com
        sub_title: Machine Learning Engineer
        caption: October 2021 - Present
        quote: >
          Solving 21st century problems by diging holes and making game changing products like the *not a flamethrower*
        description: | # this will include new lines to allow paragraphs
            Every company needs its networks properly administered and The Boring Compay is no exception. Digging holes is hard and I play my part making sure the whole company stays connected. I lead a team of 5 people and enjoy driving the company to try new technologies.

  - title: Education # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: HSE University
        caption: 2017 - 2021
        sub_title: BSc Applied Math and Information Science
        quote: >
          A quote about HSE University.
        description: | # this will include new lines to allow paragraphs
          Some description

  - title: A Little More About Me
    layout: text
    content: | # this will include new lines to allow paragraphs
      Alongside my interests in ML and SWE some of my other interests and hobbies are:
      - Rock climbing
      - Yoga
      - Surfing

      Look at this cool image  
      ![Trees](/modern-resume-theme/images/landscape-trees.jpg "Trees")

# Footer
footer_show_references: true
# references_title: References on request (Override references text)

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag

include: [".well-known"]
